repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # latest tag
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff-format
        args: ["--line-length=88"]
      - id: ruff
        args: [
          "--fix",
          "--show-fixes",
          "--select=F,W,B,I,RUF,UP",
          "--line-length=88"
        ]